### ISSUE TITLE
Quarkus 3.0.3

### ISSUE THREAD

**Issue by ralscha** [legal-i/agent-example#1]
Version 3.0.3 is available:

https://github.com/legal-i/agent-example/blob/131592936cc264576be1869c0f2bc3e5079db7d9/agent-example-quarkus/pom.xml#L15

**Comment by MatthiasWinzeler** [comment]
@ralscha thanks, didn't see that yet! Will upgrade it to latest once we finalize the example.

**Comment by MatthiasWinzeler** [comment]
@ralscha bumped to 3.1.1 in https://github.com/legal-i/agent-example/commit/708d9df6e5d97074586e3d6b2b00865abef57ed8
